### ISSUE TITLE
Physical Tasks Building for SubjuGator 2022

### ISSUE THREAD

**Issue by MechAnger** [uf-mil/mil#494] opened 2022-03-22 20:15 UTC
Someone needs to physically to start building tasks for robosub competition for summer 2022.

## Elements that need to be manufactured (Section of the Handbook)

- [x] Start gate (2.5.2)
  - [ ] Current build is not the correct dimensions or color
- [ ]  Path Marker (2.5.3)
- [ ] Bouys (2.5.4)
  - [ ] One of the images is already printed
- [ ] Bins (2.5.5
- [ ] Shootout (2.5.6
- [ ] Octagon (2.5.7)
  - [ ] Octagon
  - [ ] G-Man table
  - [ ] Bootlegger table
  - [ ] Bottle Table

- Drawings are in the Handbook linked in #608 .
- PVC pipes are inside or outside in the back of CIMAR (by the trailer).
- PVC cutter is in the main lab drawer where all the cutting tools are.
- Pictures can be put on a poster and lamination of the pictures and the pictures print outs can be done in target copy right across UF.
- Elbows and other connectors for PVC can also be found in main lab or CIMAR.
  - If not enough (which should be since last time, we have bought extra) a list can be made and it could be purchased.
- Wood planks can be found in main lab or CIMAR.

**Comment by kawaiiPlat** [comment] 2022-06-12 00:00
Elements that need to be manufactured (Section of the Handbook)
- [ ] ***Start gate (2.5.2)***
  - [ ] Current build is not the correct dimensions or color
- [ ]  ***Path Marker (2.5.3)***
- [ ] ***Bouys (2.5.4)***
  - [ ] One of the images is already printed
- [ ] ***Bins (2.5.5)***
- [ ] ***Shootout (2.5.6)***
- [ ] ***Octagon (2.5.7)***
  - [ ] Octagon
  - [ ] G-Man table
  - [ ] Bootlegger table
  - [ ] Bottle Table

**Comment by cbrxyz** [comment] 2022-07-25 23:30
Duplicate of #608

**Closed by cbrxyz** 2022-07-25 23:30 UTC
Labels: good first issue, subjugator8, mechanical, subjugator9
